<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jakubkrizka
 * Date: Sat, 11 Apr 2015 12:34:11 +0200
 */

$conf['title'] = 'Jakub Křižka wiki';
$conf['start'] = 'home';
$conf['lang'] = 'cs';
$conf['license'] = 'gnufdl';
$conf['recent'] = 0;
$conf['recent_days'] = 0;
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['signature'] = ' --- //@DATE@ [[@MAIL@|@NAME@]] //';
$conf['showuseras'] = 'username';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['passcrypt'] = 'bcrypt';
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'index,recent,revisions,register,rss,source,export_raw';
$conf['registernotify'] = 'email@jakubkrizka.cz';
$conf['userewrite'] = '2';
$conf['canonical'] = 1;
$conf['compression'] = 'bz2';
$conf['plugin']['gallery']['sort'] = 'mod';
$conf['plugin']['gallery']['options'] = 'cache,lightbox,showname,showtitle';
$conf['plugin']['captcha']['mode'] = 'math';
$conf['plugin']['translation']['copytrans'] = '1';

// end auto-generated content
